name: "Input - Installation path"

run-name: "Installation path"

on:
  push:
  pull_request:

jobs:
  default_path:
    name: "Default path"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
      
    - name: Install Jython
      uses: ./
      with:
        jython-version: "2.2"

    - name: Run Jython
      shell: bash
      run: |
        [[ -f ~/jython/jython.jar ]] || exit 1

  custom_path:
    name: "Custom path"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Install Jython
      uses: ./
      with:
        jython-version: "2.2"
        installation-path: "/tmp/jython-2.2"

    - name: Run Jython
      shell: bash
      run: |
        [[ -f "/tmp/jython-2.2/jython.jar" ]] || exit 1
